"""
PAIR (Prompt Automatic Iterative Refinement) Jailbreak Attack

Reference:
    @article{chao2023jailbreaking,
        title={Jailbreaking black box large language models in twenty queries},
        author={Chao, Patrick and Robey, Alexander and Dobriban, Edgar and Hassani, Hamed and Pappas, George J and Wong, Eric},
        journal={arXiv preprint arXiv:2310.08419},
        year={2023}
    }
"""

import json
import math
import warnings
from tqdm.auto import tqdm

from ..registry import register_jailbreak
from . import prompts


@register_jailbreak("pair")
def pair(
    prompt: str,
    target_str: str = "Sure, I'm happy to help",
    attack_models: list = None,
    victim_model: str = "gemma-3-27b-it",
    judge_models: list = None,
    max_iter: int = 20,
    max_conversation_length: int = 3,
    max_tokens: int = 1024,
    verbose: bool = False,
    **kwargs,
) -> str:
    """PAIR jailbreak attack.

    Iteratively refines prompts using an attacker LLM to jailbreak a victim LLM.

    Args:
        prompt: Forbidden prompt (the goal).
        target_str: The attack model wants the victim to output this string.
        attack_models: Attack models. Falls back to next model on failure.
        victim_model: Victim model to attack.
        judge_models: Models that judge how harmful the victim's response was.
        max_iter: Maximum number of iterations.
        max_conversation_length: Maximum conversation length in attack model's context.
        max_tokens: Maximum tokens generated by models.
        verbose: If True, print all LLM interactions. Defaults to False.

    Returns:
        Jailbroken prompt.
    """
    from ...generate import generate_response as generate
    from ...evaluators.registry import evaluate_response as evaluate
    
    # Set default attack models if not provided
    if attack_models is None:
        attack_models = ["gemma-3-27b-it"]
    
    if verbose:
        print(f"\n🎯 Starting PAIR Attack (max {max_iter} iterations)")
        print(f"Goal: {prompt}")
        print(f"Target string: {target_str}\n")
    
    best_score, best_prompt = 1, prompt
    attacker_system_prompt = prompts.get_attacker_system_prompt(
        goal=prompt, target_str=target_str
    )
    init_attacker_prompt = prompts.get_attacker_init_message(
        goal=prompt, target_str=target_str
    )
    conversation = []
    
    for iteration in (progress_bar := tqdm(range(max_iter), desc="PAIR")):
        if verbose:
            print(f"\n🔄 PAIR Iteration {iteration + 1}/{max_iter}")
        
        # Use the attacker to generate a jailbroken prompt
        jailbroken_prompt = None
        for attack_model in attack_models:
            if verbose:
                print(f"🤖 Attacker LLM ({attack_model}) generating jailbreak...")
            attacker_response = generate(
                [init_attacker_prompt] + conversation,
                attack_model,
                system_prompt=attacker_system_prompt,
                max_tokens=max_tokens,
                verbose=verbose,
            )
            try:
                # Extract JSON from response (handle markdown code blocks)
                response_text = attacker_response
                if "```json" in response_text:
                    response_text = response_text.split("```json")[1].split("```")[0]
                elif "```" in response_text:
                    response_text = response_text.split("```")[1].split("```")[0]
                
                # Try to parse JSON
                parsed = json.loads(response_text.strip())
                jailbroken_prompt = parsed.get("prompt")
                
                if jailbroken_prompt:
                    if verbose:
                        print(f"✅ Generated jailbreak prompt: {jailbroken_prompt[:200]}...")
                    break
            except Exception as e:
                if verbose:
                    print(f"❌ Failed to parse JSON from attacker: {str(e)[:100]}")
                pass

        if jailbroken_prompt is None:
            if verbose:
                print(f"⚠️ No valid jailbreak generated, skipping iteration")
            continue

        # Get victim model response and judge's evaluation
        if verbose:
            print(f"🎯 Testing jailbreak on victim model ({victim_model})...")
        victim_response = generate(jailbroken_prompt, victim_model, max_tokens=max_tokens, verbose=verbose)
        
        if verbose:
            print(f"⚖️ Evaluating response...")
        result = evaluate(
            "pair",
            prompt,
            victim_response,
            models=judge_models,
            max_tokens=max_tokens,
            verbose=verbose
        )
        score = result.get("score", 0)
        
        if math.isnan(score):
            if verbose:
                print(f"⚠️ Invalid score (NaN), skipping")
            continue

        score = 9 * score + 1  # Invert the min-max scaling; score now 1-10
        
        if verbose:
            print(f"📊 Score: {score:.2f} (best so far: {best_score:.2f})")
        
        progress_bar.set_description(
            f"PAIR Best: {max(best_score, score):.1f}, Last: {score:.1f}"
        )
        
        if score == 10:  # Maximum score achieved
            if verbose:
                print(f"🎉 Perfect score! Returning best prompt.")
            return jailbroken_prompt
        elif best_score < score:
            best_score = score
            best_prompt = jailbroken_prompt
            if verbose:
                print(f"✨ New best prompt found!")

        # Update the conversation
        target_response = prompts.get_target_response(
            target_response=victim_response, goal=prompt, score=score
        )
        conversation += [attacker_response, target_response]
        
        # Keep conversation within max length
        if 2 * max_conversation_length < len(conversation):
            conversation = conversation[2:]

    if best_score == 1:
        msg = f"PAIR failed to jailbreak for {prompt}"
        warnings.warn(msg)

    return best_prompt
